### ISSUE TITLE
Update the UI of the player section

### ISSUE THREAD

**Issue by youtanimstar** [youtanimstar/music-hub#11]
The player section on the Music Hub is not very impressive. Please update the UI while maintaining the theme of the website. Additionally, feel free to incorporate some cool animations. Here is the Player section 

![Screenshot from 2023-10-16 20-51-58](https://github.com/youtanimstar/music-hub/assets/107903218/b92bef7a-2187-4b93-9358-bb2b668590bb)

**Comment by dilini-liyanage** [comment]
I like to work on this. Can you assign this to me?

**Comment by youtanimstar** [comment]
> I like to work on this. Can you assign this to me?

Sure, @dilini-liyanage  but please finish issue #15  first.
Happy Coding...!!
