### ISSUE TITLE
Update the side bar's UI

### ISSUE THREAD

**Issue by youtanimstar** [youtanimstar/music-hub#15]
On the Music Hub website, the UI of the sidebar is not very impressive. Here is a screenshot of the sidebar.

![Screenshot from 2023-10-16 21-36-52](https://github.com/youtanimstar/music-hub/assets/107903218/4a4de12b-3e18-4c8e-9fcd-60cada836678)

**Comment by dilini-liyanage** [comment]
I like to work on this. Can you assign this to me?

**Comment by youtanimstar** [comment]
> I like to work on this. Can you assign this to me?

Sure, please proceed @dilini-liyanage 
Happy Coding...!!
