### ISSUE TITLE
Add more functions to the play list page

### ISSUE THREAD

**Issue by youtanimstar** [youtanimstar/music-hub#20]
In the playlist section, there are very few options visible. Please add more options, such as:
- Shuffle music
- Play as a Queue
- Like any music
and so on. Feel free to add other options if you'd like. Here is the screenshot of the playlist section

![Screenshot from 2023-10-17 11-06-25](https://github.com/youtanimstar/music-hub/assets/107903218/883f6104-833e-4ee0-ad8f-e0d790a3ffa7)

**Comment by sushma1031** [comment]
Hello, I'd like to work on this.

**Comment by youtanimstar** [comment]
> Hello, I'd like to work on this. Since the 'like' option has a separate issue for itself, can I work on the shuffle and play as a queue options?

Sure, please proceed @sushma1031 
Happy Coding...!!

**Comment by sushma1031** [comment]
Could you please help me with setting up the project locally? I've forked and cloned the repo, but when I open the `index.html`, it doesn't show all the content that's there in the hosted website link provided.
Could you let me know where I'm going wrong?
Screenshot:
<img width="960" alt="Screenshot (147)" src="https://github.com/youtanimstar/music-hub/assets/123486589/750d197d-b032-4f8d-a64b-1fd69838be2b">

**Comment by youtanimstar** [comment]
First, check whether your forked repo is updated or not. To do this, follow these steps:

- Click the 'Sync fork' button.

![Screenshot from 2023-10-17 14-45-50](https://github.com/youtanimstar/music-hub/assets/107903218/4318d608-f39a-44c9-a981-2e9cbc7d10f6)

- Update the branch.

![Screenshot from 2023-10-17 14-45-59](https://github.com/youtanimstar/music-hub/assets/107903218/a2994795-7a68-4b97-bc5b-39bf44fcf535)

- Click on the 'Code' option, copy the link, and create a new file to clone this repo. If you want to continue with the previously cloned file, simply pull it from the repo.

-  If this process doesn't work, delete your forked repo and fork it again. I think this should work.
-  If this doesn't work either, make sure you have enabled JavaScript in your browser.

**Comment by sushma1031** [comment]
All right, I'll try those steps, thank you.

**Comment by sushma1031** [comment]
I tried all the steps, I'm afraid it's still not working. Here's the error I'm getting:
<img width="960" alt="Screenshot (148)" src="https://github.com/youtanimstar/music-hub/assets/123486589/a8011319-bb3b-49f2-958b-62185269d92f">

Sorry for the inconvenience, if you could help me through this I'll start working on the features right away

**Comment by youtanimstar** [comment]
@sushma1031 
I think I have solved this error. I usually perform this type of work in VS Code with the Live Server extension. So, I cannot understand why this error is showing. However, when I run the index.html file locally from my system, I encounter the same errors. Therefore, I suggest you open these files in VS Code and run them using Live Server.

**Comment by sushma1031** [comment]
@youtanimstar I did what you suggested and it's working perfectly now, thank you!
