### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by manish-bhukar** [youtanimstar/music-hub#24]
I seen that copyright year is not dynamic it fix 2023 and remain fix even in 2024 for making it dynamic give me this issue .
<img width="323" alt="image" src="https://github.com/youtanimstar/music-hub/assets/125037273/b05b1ddc-3afd-48b4-96d6-a22d14ebd6ef">

**Comment by youtanimstar** [comment]
> I seen that copyright year is not dynamic it fix 2023 and remain fix even in 2024 for making it dynamic give me this issue . <img alt="image" width="323" src="https://user-images.githubusercontent.com/125037273/275738184-b05b1ddc-3afd-48b4-96d6-a22d14ebd6ef.png">

Sure, please proceed @manish-bhukar 
Happy Coding...!!
