### ISSUE TITLE
Unnecessary and Unappealing Sidebar under Carousel Section

### ISSUE THREAD

**Issue by dev-palwar** [youtanimstar/music-hub#25]
## Context
The sidebar under the carousel section does not look good and it also serves no purpose when there are buttons to slide the carousel

https://github.com/youtanimstar/music-hub/assets/102988552/313db9f3-4b22-41c9-8a73-0ea8592b4faf

## Would you like to work on this issue?
Yes

**Comment by youtanimstar** [comment]
> ## Context
> The sidebar under the carousel section does not look good and it also serves no purpose when there are buttons to slide the carousel
> 
>  Music.Hub.Mozilla.Firefox.2023-10-17.14-29-29.mp4 
> ## Would you like to work on this issue?
> Yes

Yeah, sure! You can disable the sidebar. While creating this website, I used the Chrome browser, so the sidebar is not visible. However, if the Firefox browser displays this type of sidebar, please disable it @dev-palwar 
Happy Coding !!
