### ISSUE TITLE
[BUG]: Guiding user to register before Login

### ISSUE THREAD

**Issue by AnujRathour** [youtanimstar/music-hub#33]
This issue is about when user is on login page  and he is trying to login  but he has not register yet. Then, guide the user on login page he has to register first then  login.  And also changing the `submit` button  text by `login or signin`.
<img width="471" alt="Screenshot 2023-10-18 114147" src="https://github.com/youtanimstar/music-hub/assets/119128989/e10d1766-eaf1-4b77-8b76-940922ed8f07">

**Comment by AnujRathour** [comment]
@youtanimstar I would like to work on this issue please assign it to me.

**Comment by youtanimstar** [comment]
> @youtanimstar I would like to work on this issue please assign it to me.

Sure, please proceed @AnujRathour 
Happy Coding..!!
