### ISSUE TITLE
Adding a Click event and hover on the song tab 

### ISSUE THREAD

**Issue by DannyK05** [youtanimstar/music-hub#34]
I want to add a Click event that shows on the music tab that the song as been selected.

 ![IMG_20231018_081533.jpg](https://github.com/youtanimstar/music-hub/assets/105021997/dc1f6aec-6594-40c1-bbc8-b6e039857cae)

Probably like a text color change and addition of the wavy bars on the song tab

**Comment by taran1326** [comment]
hey I want to work on this , can you assign me the task ?
and can you please add hacktober fest tag on the issue ?

**Comment by youtanimstar** [comment]
> I want to add a Click event that shows on the music tab that the song as been selected.
> 

Sure, please proceed @DannyK05 
Happy Coding..!!

**Comment by DannyK05** [comment]
I will, thanks @youtanimstar

**Comment by youtanimstar** [comment]
> @youtanimstar Can u assign me this ??

Sorry @DeepRahangdale , I have already assigned this issue to @DannyK05. If you want to work on another issue, please raise a new issue, and I will assign it to you.

**Comment by DannyK05** [comment]
Hi @youtanimstar 
I've been trying to work on this  issue since yesterday
But after i cloned it doesn't display any tabs on my browser
![image](https://github.com/youtanimstar/music-hub/assets/105021997/8b9b1eb4-02c4-42a7-9bd3-c92b0303234a)
 and I get this error on my console do you know I can fix this
 
![image](https://github.com/youtanimstar/music-hub/assets/105021997/41723442-5959-4314-8c2e-89db9549b5df)

**Comment by DeepRahangdale** [comment]
@DannyK05 run the index.html file using the Live Server(You will find the extension in the Vs code).

**Comment by DannyK05** [comment]
> @DannyK05 run the index.html file using the Live Server(You will find the extension in the Vs code).

It works now
Thanks @DeepRahangdale
