### ISSUE TITLE
Fix : Fixing footer position on library and about us page

### ISSUE THREAD

**Issue by yube01** [youtanimstar/music-hub#37]
In library and about us page , footer is not present on the bottom of the screen

It would be better if they are positioned on the bottom position

**Comment by aliveevie** [comment]
#37

**Comment by youtanimstar** [comment]
> In library and about us page , footer is not present on the bottom of the screen
> 
> It would be better if they are positioned on the bottom position

@yube01 Please provide a screenshot of your issue
