### ISSUE TITLE
Adding a Hover Effect over Popular Artist Icons

### ISSUE THREAD

**Issue by DeepRahangdale** [youtanimstar/music-hub#46]
add a hacktoberfest tag!!
and assign me this

**Comment by youtanimstar** [comment]
> add a hacktoberfest tag!! and assign me this

Sure , please proceed @DeepRahangdale 
Happy Coding..!!

**Comment by DeepRahangdale** [comment]
@youtanimstar i am not able to see the icons in latest song and popular artist as i open the index.html
