### ISSUE TITLE
For mobile/small devices in footer section Social links is outside Footer!! 

### ISSUE THREAD

**Issue by DeepRahangdale** [youtanimstar/music-hub#47]
Add under Hacktoberfest!!!
https://drive.google.com/file/d/1XCuXVKm6fmM9903_GeqA7wmlCRC7NRCX/view?usp=sharing

**Comment by youtanimstar** [comment]
> Add under Hacktoberfest!!! https://drive.google.com/file/d/1XCuXVKm6fmM9903_GeqA7wmlCRC7NRCX/view?usp=sharing

Indeed, these minor changes may not significantly enhance the project. If you wish to proceed, you may do so. @DeepRahangdale
