### ISSUE TITLE
Make the navbar responsive

### ISSUE THREAD

**Issue by youtanimstar** [youtanimstar/music-hub#8]
The navbar section on the Music Hub website is not responsive. Here is a screenshot of the navbar

![Screenshot from 2023-10-16 20-37-18](https://github.com/youtanimstar/music-hub/assets/107903218/c8fc2d1b-fb71-4955-b948-30bec0935ae8)

**Comment by youtanimstar** [comment]
> Can you assign me this issue? I would like to work on it. @youtanimstar

Sure, please proceed @An-Array .
Happy Coding...!!

**Comment by ishanwadhwani** [comment]
is it completed yet? or I can contribute?
