### ISSUE TITLE
Make the home page responsive

### ISSUE THREAD

**Issue by youtanimstar** [youtanimstar/music-hub#9]
The home page section on the Music Hub website is not responsive. Here is a screenshot of the home page

![Screenshot from 2023-10-16 20-43-32](https://github.com/youtanimstar/music-hub/assets/107903218/fa92aec6-25e1-4eed-9031-7f960d7536c2)

**Comment by madmaxWMFU** [comment]
Hi! I can try this) Can you assign it for me?

**Comment by youtanimstar** [comment]
> Hi! I can try this) Can you assign it for me?

Sure, please proceed @madmaxWMFU 
Happy Coding...!!

**Comment by Tulsi5990** [comment]
Hey can you assign me this work
